### ISSUE TITLE
paramiko not installed?

### ISSUE THREAD

**Issue by baffonso** [ownport/portable-ansible#10]
When trying to use paramiko to get around sshpass issue, I get the following message:

 python ansible test -m ping --ask-pass -c paramiko
[DEPRECATION WARNING]: DEFAULT_SUDO_EXE option, In favor of Ansible Become, which is a generic framework. See become_exe. , use become instead. This feature will be removed in version 2.8.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
SSH password:
test | FAILED! => {
    "msg": "paramiko is not installed"
}

**Comment by ownport** [comment]
Hm, interesting
```
$ python3 ansible localhost -m ping --ask-pass -c paramiko
SSH password: 
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
$ pip3 freeze | grep paramiko
$
```
as you can see paramiko is not installed on my system. What is OS you are using?

**Comment by ownport** [comment]
as no comments for the issue, I will close it. Please re-open if the question is still actual and we continue discussion
