### ISSUE TITLE
 "paramiko is not installed: No module named enum"

### ISSUE THREAD

**Issue by blackhawksj** [ownport/portable-ansible#14]
Hi @ownport , Greetings 
I was trying out the released (0.3) of the portable ansible. Configured it to use paramiko as the transport , but when executing the playbook it says  {"msg": "paramiko is not installed: No module named enum"}

any suggestion would be very helpful.

**Comment by blackhawksj** [comment]
Using python 2.7 (centos 7 minimal install)
-sh-4.2$ python ansible --version
ansible 2.8.0
  config file = /home/527888/.ansible/linux-hardening-playbooks/scripts/ansible.cfg
  configured module search path = [u'/home/527888/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/527888/.ansible/linux-hardening-playbooks/scripts/ansible/ansible
  executable location = ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
-sh-4.2$

**Comment by ownport** [comment]
@blackhawksj sorry, I will be busy during this week, can check during weekend. Could you please describe your scenario? Are you connecting to remote host, right?

**Comment by blackhawksj** [comment]
no problem @ownport , yes I'm connecting to remote host, the need was sshpass would not be installed on the host(ansible runner) so username/password based playbook execution will not work.
So to use the alternative I changed the transport to paramiko  in the ansible.cfg file. Then it is giving this error. 
Checked the same settings on the same server with an installed ansible (yum install ansible), it was working there.

**Comment by ownport** [comment]
unfortunately, I cannot simulate your issue on my side but I published new version of portable ansible based on ansible 2.8.5 and added several components for working with username/password via paramiko. My test environment described in test/ https://github.com/ownport/portable-ansible/tree/master/test/docker. There are server and ansible runner images with few simple playbooks for access to server via ssh keys and username/password. Could you please check new version and I will appreciate for feedback. Thanks

**Comment by blackhawksj** [comment]
thanks, i'll check and let you know

**Comment by blackhawksj** [comment]
@ownport ownport Hi, Same error with 8.5 too.

**Comment by ownport** [comment]
```
Using python 2.7 (centos 7 minimal install)
```
@blackhawksj  are you using minimal python installation?

**Comment by ownport** [comment]
@blackhawksj I've created new docker image with centos:7 and now I can simulate your case. I will check it later, let you know

**Comment by ownport** [comment]
@blackhawksj new version of portable-ansible with fix for py2 is available, https://github.com/ownport/portable-ansible/releases/tag/v0.3.2

**Comment by blackhawksj** [comment]
Hi @ownport Thanks, this new version , paramiko works, however it is giving  CryptographyDeprecationWarning. the issue has been fixed in version 2.5.0
https://github.com/paramiko/paramiko/issues/1386.

I'm closing the issue though as paramiko connector works.

**Comment by ownport** [comment]
thanks @blackhawksj I will update paramiko's version in next version of portable ansible
