### ISSUE TITLE
Ansible-vault doesn't work

### ISSUE THREAD

**Issue by roxor45** [ownport/portable-ansible#17]
Hello, 

I try to use ansible-vault , but I have a mysterious problem: 

first , I create a symbolic link ansible-vault to ansible

and when I try to encrypt ( or create / edit  ) , I get this error, 

```
ansible-vault 2.7.8
  config file = /opt/autom/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/ansible
  executable location = ansible-vault
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /opt/autom/ansible.cfg as config file
New Vault password:
Confirm New Vault password:
ERROR! ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function.
```
Do have a way for fix it  pls ?

thanks a lot

**Comment by ownport** [comment]
There are some limitations of portable-ansible approach. ansible-vault requires one of the modules `cryptography` or `pycrypto`. Both of them depends on pre-compiled modules which are depends on host system configuration.

**Comment by ownport** [comment]
@roxor45 if no objections I will close the ticket
