### ISSUE TITLE
Support for Ansible 2.10?

### ISSUE THREAD

**Issue by SiqingYu** [ownport/portable-ansible#18]
Hi Ansible guys, I have been using portable-ansible recently without any problem. Until I found a needed parameter of the `mysql_user` module, which was new in Ansible 2.10.

Do you guys have any plan for Ansible 2.10?

**Comment by ownport** [comment]
ansible 2.10.5 was added as part 0.5.0 release https://github.com/ownport/portable-ansible/releases/tag/v0.5.0

**Comment by SiqingYu** [comment]
Thanks. It is very timely.

**Comment by SiqingYu** [comment]
However, I found the Python 2 build was removed. In our case, the customers' systems only have Python 2. I build the Python 2 tarball with Ansible 2.10, and it works without problem, except for a warning of the deprecated `cryptography` package.
