### ISSUE TITLE
ansible-v2.3.0.0-1

### ISSUE THREAD

**Issue by ownport** [ownport/portable-ansible#2]

**Comment by mmarek** [comment]
Would you make another release please?

**Comment by ownport** [comment]
I would be interesting to try new version 2.3. I will try

**Comment by ownport** [comment]
Done, https://github.com/ownport/portable-ansible/releases/tag/ansible-2.3.0.0

**Comment by ownport** [comment]
@mmarek  Please let me if I can close the issue?

**Comment by mmarek** [comment]
Hi, thanks for response, you can close it.

I have a very odd use case that i need a config managment tool without
dependencies(to download tarball and run like: [provisioner] --apply
configuration.yml. Python is usually available but pip, paramiko etc. can
be problematic.

I am testing saltstack at the moment for this, as it only needs yaml and
jinja.

2017-05-01 7:47 GMT+02:00 Andrey Usov <notifications@github.com>:

**Comment by ownport** [comment]
@mmarek you can download only https://github.com/ownport/portable-ansible/releases/download/ansible-2.3.0.0/ansible.tar.bz2. This tarball already contains all required libs. 

Regarding saltstack, it is really interesting use case. My understanding was that the saltstack requires much more deps. I will review it. Thanks for this idea.

**Comment by ownport** [comment]
Added details about how to install and use in the README https://github.com/ownport/portable-ansible#how-to-install-and-use

**Comment by mmarek** [comment]
Usually paramiko is the painful dependency.
Due to openssl requirements and rebuilding. Saltstack operates outside ssh
thus all other deps are easily bundleable(mosly pyaml, jinja, safemarkup
etc very much portable).

In ansible if you go down the path of optional paramiko you are not allowed
to use shell module, which is plenty useful.

2017-05-01 14:59 GMT+02:00 Andrey Usov <notifications@github.com>:

**Comment by ownport** [comment]
How are you solving deps with tornado in saltstack case?

**Comment by mmarek** [comment]
i pull them from site-packages to current pythonpath,
So far i tested rhel 6.x, 7.x, sles 11.x, 12.x and everything seems fine,
as long as there is > python 2.6
Compressed (gz) tarball has about 10mb.


2017-05-02 19:15 GMT+02:00 Andrey Usov <notifications@github.com>:

**Comment by mmarek** [comment]
Whats your usecase for portable ansible?
Salt for me is kinda fine... its very anal about having proper structure in
rootfs, /srv/sallt /etc/salt/minion_id, but besides its not super painful
to have it portable and its fully operational.

2017-05-02 19:20 GMT+02:00 Marek Mollin <roguas@gmail.com>:

**Comment by ownport** [comment]
> Whats your usecase for portable ansible?

different automations for single node where is no admin rights. Thanks for sharing your experience, very intersting
