### ISSUE TITLE
Tarball building procedure

### ISSUE THREAD

**Issue by 414n** [ownport/portable-ansible#4]
Greetings,

it is not clear how the release tarball is built with the given Makefile. From what I can see, all that the Makefile builds is a script with an embedded zipfile, that I couldn't get to work...

**Comment by ownport** [comment]
You just need to run 
```sh
$ make prepare
```
the directory ansible will contain all required packages

**Comment by ownport** [comment]
the compilation to zipped archive is not working for ansible as the ansible logic uses file system for getting modules and plugins

**Comment by 414n** [comment]
Thanks for the explanation, now I have a grasp of the situation.
Mind if I later submit a PR to add an explicit tarball target to the Makefile? 😉

**Comment by ownport** [comment]
Feel free

**Comment by 414n** [comment]
Looking better at the packaged contents, I think there's still a little issue: the markup-safe dependency for jinja2 pulls in native code in `ansible/markupsafe/_speedups.so`. This makes the package not so platform-independent anymore as it would've been for a 100% pure python package.
Maybe the platform and architecture should be added to the tarball name?

**Comment by ownport** [comment]
Good catch! I'm going a little bit to change the structure of the project to make it more clear

**Comment by ownport** [comment]
https://github.com/ownport/portable-ansible/releases/tag/v0.5.0
